name: ml_fundamentals
channels:
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - contourpy=1.2.0
  - cycler=0.11.0
  - expat=2.6.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - joblib=1.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pandas=2.2.1
  - pillow=10.3.0
  - pip=24.0
  - pybind11-abi=5
  - pyparsing=3.0.9
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.3.0
  - scipy=1.13.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - tornado=6.3.3
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
